name: Code quality check
run-name: Check code quality with Linters
on: [push]
jobs:
    Detekt:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

            -   name: set up JDK
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: 17

            -   uses: gradle/gradle-build-action@v3
                with:
                    cache-disabled: true

            - name: Publish detekt reports
              shell: bash
              run: ./gradlew detekt

              uses: jwgmeligmeyling/checkstyle-github-action@master
              with:
                  path: '**/detekt.xml'